# Generated by Django 3.2.9 on 2021-11-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_recipe_name_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('1', 'University'), ('2', 'Maktab'), ('3', 'Usual life'), ('4', 'entertainment'), ('5', 'others')], default='1', max_length=1),
        ),
    ]
