# Generated by Django 3.2.9 on 2021-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20211123_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', 'University'), ('2', 'Maktab'), ('3', 'Usual life'), ('4', 'Entertainment'), ('5', 'Others')], default='1', max_length=1),
        ),
    ]
