# Generated by Django 3.2.9 on 2021-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', '1'), ('Medium', '2'), ('Low', '3')], default='Medium', max_length=6),
        ),
    ]
